"""add_pod_status_enum

Revision ID: 20240919014800
Revises: x43fd96f85b9
Create Date: 2024-09-19 01:48:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240919014800"
down_revision = "x43fd96f85b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # status column already exists, skip adding it
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pods", "status")
    # ### end Alembic commands ###
