"""add_notification_enabled_to_follows

Revision ID: 20251008000000
Revises: 20250115000000
Create Date: 2025-10-08 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251008000000"
down_revision = "20250115000000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # notification_enabled 컬럼 추가 (기본값 TRUE)
    op.add_column(
        "follows",
        sa.Column(
            "notification_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="1",
            comment="알림 활성화 여부",
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # notification_enabled 컬럼 삭제
    op.drop_column("follows", "notification_enabled")

    # ### end Alembic commands ###
