"""remove_full_status_from_podstatus

Revision ID: 20250115000000
Revises: 20240919014800
Create Date: 2025-01-15 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20250115000000"
down_revision = "20240919014800"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. FULL 상태인 파티들을 COMPLETED로 변경
    op.execute("UPDATE pods SET status = 'completed' WHERE status = 'full'")

    # 2. 새로운 ENUM 타입 생성 (FULL 제거)
    op.execute(
        "ALTER TABLE pods MODIFY COLUMN status ENUM('recruiting', 'completed', 'closed') NOT NULL DEFAULT 'recruiting'"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 기존 ENUM 타입 삭제
    op.execute("ALTER TABLE pods DROP CONSTRAINT pods_status_check")

    # 2. 원래 ENUM 타입 복원 (FULL 포함)
    op.execute(
        "ALTER TABLE pods MODIFY COLUMN status ENUM('recruiting', 'full', 'completed', 'closed') NOT NULL DEFAULT 'recruiting'"
    )

    # ### end Alembic commands ###
