"""add_notification_table

Revision ID: 20251011000000
Revises: 20251008000002
Create Date: 2025-10-11 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251011000000"
down_revision = "20251008000002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # notifications 테이블 생성
    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="받는 사람 ID",
        ),
        sa.Column(
            "title",
            sa.String(100),
            nullable=False,
            comment="알림 제목",
        ),
        sa.Column(
            "body",
            sa.Text(),
            nullable=False,
            comment="알림 내용",
        ),
        sa.Column(
            "notification_type",
            sa.String(50),
            nullable=False,
            comment="알림 타입 (예: PodNotificationType)",
        ),
        sa.Column(
            "notification_value",
            sa.String(50),
            nullable=False,
            comment="알림 값 (예: POD_JOIN_REQUEST)",
        ),
        sa.Column(
            "related_id",
            sa.String(50),
            nullable=True,
            comment="관련 ID (pod_id, review_id 등)",
        ),
        sa.Column(
            "is_read",
            sa.Boolean(),
            nullable=False,
            default=False,
            comment="읽음 여부",
        ),
        sa.Column(
            "read_at",
            sa.DateTime(),
            nullable=True,
            comment="읽은 시간",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="알림 생성 시간",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
    )

    # 인덱스 생성
    op.create_index(
        op.f("ix_notifications_id"),
        "notifications",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_is_read"),
        "notifications",
        ["is_read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 인덱스 삭제
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(
        op.f("ix_notifications_notification_type"), table_name="notifications"
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")

    # notifications 테이블 삭제
    op.drop_table("notifications")

    # ### end Alembic commands ###
