"""add_category_to_notifications

Revision ID: 20251011000001
Revises: 20251011000000
Create Date: 2025-10-11 00:00:01.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251011000001"
down_revision = "20251011000000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # category 컬럼 추가
    op.add_column(
        "notifications",
        sa.Column(
            "category",
            sa.String(20),
            nullable=False,
            server_default="pod",
            comment="알림 카테고리 (pod, community, notice)",
        ),
    )

    # category 인덱스 생성
    op.create_index(
        op.f("ix_notifications_category"),
        "notifications",
        ["category"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # category 인덱스 삭제
    op.drop_index(op.f("ix_notifications_category"), table_name="notifications")

    # category 컬럼 삭제
    op.drop_column("notifications", "category")

    # ### end Alembic commands ###
