"""add_is_del_to_users

Revision ID: 20251117000002
Revises: 20251117000001
Create Date: 2025-11-17 00:00:02.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251117000002"
down_revision = "20251117000001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # is_del 컬럼 추가
    op.add_column(
        "users",
        sa.Column("is_del", sa.Boolean(), nullable=False, server_default="0"),
    )
    # 인덱스 추가
    op.create_index("ix_users_is_del", "users", ["is_del"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 인덱스 제거
    op.drop_index("ix_users_is_del", table_name="users")
    # 컬럼 제거
    op.drop_column("users", "is_del")
    # ### end Alembic commands ###
