"""add_terms_accepted_to_users

Revision ID: 20251119000000
Revises: y44fd96f85b9
Create Date: 2025-11-19 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251119000000"
down_revision = "20251117000002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # terms_accepted 컬럼 추가
    op.add_column(
        "users",
        sa.Column("terms_accepted", sa.Boolean(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 컬럼 제거
    op.drop_column("users", "terms_accepted")
    # ### end Alembic commands ###
