"""add_related_pod_id_to_notifications

Revision ID: 20251011000003
Revises: 20251011000002
Create Date: 2025-10-11 00:00:03.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251011000003"
down_revision = "20251011000002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # related_pod_id 컬럼 추가
    op.add_column(
        "notifications",
        sa.Column(
            "related_pod_id",
            sa.Integer(),
            nullable=True,
            comment="관련 파티 ID",
        ),
    )

    # related_pod_id 외래키 제약조건 추가
    op.create_foreign_key(
        "fk_notifications_related_pod_id",
        "notifications",
        "pods",
        ["related_pod_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # related_pod_id 인덱스 생성
    op.create_index(
        op.f("ix_notifications_related_pod_id"),
        "notifications",
        ["related_pod_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # related_pod_id 인덱스 삭제
    op.drop_index(op.f("ix_notifications_related_pod_id"), table_name="notifications")

    # related_pod_id 외래키 제약조건 삭제
    op.drop_constraint(
        "fk_notifications_related_pod_id", "notifications", type_="foreignkey"
    )

    # related_pod_id 컬럼 삭제
    op.drop_column("notifications", "related_pod_id")

    # ### end Alembic commands ###
