"""create_user_notification_settings

Revision ID: 20251011000004
Revises: 20251011000003
Create Date: 2025-10-11 00:00:04.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251011000004"
down_revision = "20251011000003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # user_notification_settings 테이블 생성
    op.create_table(
        "user_notification_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="사용자 ID",
        ),
        sa.Column(
            "notice_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="1",
            comment="공지 알림 활성화",
        ),
        sa.Column(
            "pod_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="1",
            comment="파티 알림 활성화",
        ),
        sa.Column(
            "community_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="1",
            comment="커뮤니티 알림 활성화",
        ),
        sa.Column(
            "chat_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="1",
            comment="채팅 알림 활성화",
        ),
        sa.Column(
            "do_not_disturb_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="0",
            comment="방해금지 모드 활성화",
        ),
        sa.Column(
            "do_not_disturb_start",
            sa.Time(),
            nullable=True,
            comment="방해금지 시작 시간 (HH:MM)",
        ),
        sa.Column(
            "do_not_disturb_end",
            sa.Time(),
            nullable=True,
            comment="방해금지 종료 시간 (HH:MM)",
        ),
        sa.Column(
            "marketing_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="0",
            comment="마케팅 알림 수신 동의",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
    )

    # 인덱스 생성
    op.create_index(
        op.f("ix_user_notification_settings_id"),
        "user_notification_settings",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_notification_settings_user_id"),
        "user_notification_settings",
        ["user_id"],
        unique=True,  # 1:1 관계
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 인덱스 삭제
    op.drop_index(
        op.f("ix_user_notification_settings_user_id"),
        table_name="user_notification_settings",
    )
    op.drop_index(
        op.f("ix_user_notification_settings_id"),
        table_name="user_notification_settings",
    )

    # user_notification_settings 테이블 삭제
    op.drop_table("user_notification_settings")

    # ### end Alembic commands ###
