"""add_canceled_status_to_podstatus

Revision ID: 20251117000000
Revises: 20250115000000
Create Date: 2025-11-17 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251117000000"
down_revision = "20250115000000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # CANCELED 상태 추가
    op.execute(
        "ALTER TABLE pods MODIFY COLUMN status ENUM('recruiting', 'completed', 'closed', 'canceled') NOT NULL DEFAULT 'recruiting'"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # CANCELED 상태 제거 (CANCELED 상태인 파티들을 CLOSED로 변경)
    op.execute("UPDATE pods SET status = 'closed' WHERE status = 'canceled'")

    # ENUM 타입에서 CANCELED 제거
    op.execute(
        "ALTER TABLE pods MODIFY COLUMN status ENUM('recruiting', 'completed', 'closed') NOT NULL DEFAULT 'recruiting'"
    )

    # ### end Alembic commands ###
