"""add artist fields and related tables

Revision ID: 479b38d71931
Revises: c3d2e62dc28d
Create Date: 2025-09-09 17:45:22.813319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '479b38d71931'
down_revision = 'c3d2e62dc28d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('blip_artist_id', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('is_filter', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_artists_blip_artist_id'), 'artists', ['blip_artist_id'], unique=False)
    op.create_index(op.f('ix_artists_unit_id'), 'artists', ['unit_id'], unique=False)
    op.drop_column('artists', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('profile_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True))
    op.drop_index(op.f('ix_artists_unit_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_blip_artist_id'), table_name='artists')
    op.drop_column('artists', 'is_filter')
    op.drop_column('artists', 'blip_artist_id')
    op.drop_column('artists', 'unit_id')
    op.drop_column('artists', 'is_active')
    # ### end Alembic commands ###
