"""Initial migration for MySQL

Revision ID: c3d2e62dc28d
Revises: 2916265d454a
Create Date: 2025-09-06 20:08:31.287314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d2e62dc28d'
down_revision = '2916265d454a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
