"""add message and timestamp to pod members

Revision ID: y44fd96f85b9
Revises: x43fd96f85b9
Create Date: 2025-10-02 02:30:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "y44fd96f85b9"
down_revision = "x43fd96f85b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add message column
    op.add_column(
        "pod_members",
        sa.Column("message", sa.Text(), nullable=True, comment="참여 신청 메시지"),
    )

    # Modify joined_at column from DateTime to Integer
    op.alter_column(
        "pod_members",
        "joined_at",
        existing_type=mysql.DATETIME(),
        type_=sa.Integer(),
        nullable=False,
        comment="참여 신청 시간 (Unix timestamp)",
    )

    # Update existing records to have current timestamp
    op.execute(
        "UPDATE pod_members SET joined_at = UNIX_TIMESTAMP(joined_at) WHERE joined_at IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove message column
    op.drop_column("pod_members", "message")

    # Convert joined_at back to DateTime
    op.alter_column(
        "pod_members",
        "joined_at",
        existing_type=sa.Integer(),
        type_=mysql.DATETIME(),
        nullable=True,
    )
    # ### end Alembic commands ###
