"""create_user_blocks_table

Revision ID: 20251008000001
Revises: 20251008000000
Create Date: 2025-10-08 00:00:01.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251008000001"
down_revision = "20251008000000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # user_blocks 테이블 생성
    op.create_table(
        "user_blocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "blocker_id",
            sa.Integer(),
            nullable=False,
            comment="차단을 수행한 사용자 ID",
        ),
        sa.Column(
            "blocked_id",
            sa.Integer(),
            nullable=False,
            comment="차단당한 사용자 ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="차단 생성 시간",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["blocker_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["blocked_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("blocker_id", "blocked_id", name="unique_user_block"),
    )

    # 인덱스 생성
    op.create_index(
        op.f("ix_user_blocks_blocker_id"), "user_blocks", ["blocker_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_blocks_blocked_id"), "user_blocks", ["blocked_id"], unique=False
    )
    op.create_index(op.f("ix_user_blocks_id"), "user_blocks", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 인덱스 삭제
    op.drop_index(op.f("ix_user_blocks_id"), table_name="user_blocks")
    op.drop_index(op.f("ix_user_blocks_blocked_id"), table_name="user_blocks")
    op.drop_index(op.f("ix_user_blocks_blocker_id"), table_name="user_blocks")

    # user_blocks 테이블 삭제
    op.drop_table("user_blocks")

    # ### end Alembic commands ###

