"""change_pod_status_enum_to_uppercase

Revision ID: 20251117000001
Revises: 20251117000000
Create Date: 2025-11-17 00:00:01.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251117000001"
down_revision = "20251117000000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 기존 소문자 데이터를 대문자로 변경
    op.execute("UPDATE pods SET status = 'RECRUITING' WHERE status = 'recruiting'")
    op.execute("UPDATE pods SET status = 'COMPLETED' WHERE status = 'completed'")
    op.execute("UPDATE pods SET status = 'CLOSED' WHERE status = 'closed'")
    op.execute("UPDATE pods SET status = 'CANCELED' WHERE status = 'canceled'")

    # 2. ENUM 타입을 대문자로 변경
    op.execute(
        "ALTER TABLE pods MODIFY COLUMN status ENUM('RECRUITING', 'COMPLETED', 'CLOSED', 'CANCELED') NOT NULL DEFAULT 'RECRUITING'"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 기존 대문자 데이터를 소문자로 변경
    op.execute("UPDATE pods SET status = 'recruiting' WHERE status = 'RECRUITING'")
    op.execute("UPDATE pods SET status = 'completed' WHERE status = 'COMPLETED'")
    op.execute("UPDATE pods SET status = 'closed' WHERE status = 'CLOSED'")
    op.execute("UPDATE pods SET status = 'canceled' WHERE status = 'CANCELED'")

    # 2. ENUM 타입을 소문자로 변경
    op.execute(
        "ALTER TABLE pods MODIFY COLUMN status ENUM('recruiting', 'completed', 'closed', 'canceled') NOT NULL DEFAULT 'recruiting'"
    )

    # ### end Alembic commands ###
