"""add unit_id to artist tables

Revision ID: x43fd96f85b9
Revises: 2916265d454a
Create Date: 2025-01-09 17:58:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'x43fd96f85b9'
down_revision: Union[str, None] = '479b38d71931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # artist_images 테이블에 unit_id 컬럼 추가 (NOT NULL)
    op.add_column('artist_images', sa.Column('unit_id', sa.Integer(), nullable=False, server_default='0'))
    
    # artist_members 테이블에 unit_id 컬럼 추가 (NOT NULL)
    op.add_column('artist_members', sa.Column('unit_id', sa.Integer(), nullable=False, server_default='0'))
    
    # 기본값 제거 (실제 데이터가 들어가면 덮어씀)
    op.alter_column('artist_images', 'unit_id', server_default=None)
    op.alter_column('artist_members', 'unit_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # artist_members 테이블에서 unit_id 컬럼 제거
    op.drop_column('artist_members', 'unit_id')
    
    # artist_images 테이블에서 unit_id 컬럼 제거
    op.drop_column('artist_images', 'unit_id')
    # ### end Alembic commands ###
