"""create_user_reports_table

Revision ID: 20251008000002
Revises: 20251008000001
Create Date: 2025-10-08 00:00:02.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251008000002"
down_revision = "20251008000001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # user_reports 테이블 생성
    op.create_table(
        "user_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "reporter_id",
            sa.Integer(),
            nullable=False,
            comment="신고를 수행한 사용자 ID",
        ),
        sa.Column(
            "reported_user_id",
            sa.Integer(),
            nullable=False,
            comment="신고당한 사용자 ID",
        ),
        sa.Column(
            "report_types",
            sa.JSON(),
            nullable=False,
            comment="신고 유형 ID 목록 (최대 3개)",
        ),
        sa.Column(
            "reason",
            sa.String(500),
            nullable=True,
            comment="신고 이유 (추가 설명)",
        ),
        sa.Column(
            "blocked",
            sa.Boolean(),
            nullable=False,
            comment="신고와 함께 차단 여부",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="신고 생성 시간",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reported_user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
    )

    # 인덱스 생성
    op.create_index(
        op.f("ix_user_reports_reporter_id"),
        "user_reports",
        ["reporter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_reports_reported_user_id"),
        "user_reports",
        ["reported_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_user_reports_id"), "user_reports", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 인덱스 삭제
    op.drop_index(op.f("ix_user_reports_id"), table_name="user_reports")
    op.drop_index(op.f("ix_user_reports_reported_user_id"), table_name="user_reports")
    op.drop_index(op.f("ix_user_reports_reporter_id"), table_name="user_reports")

    # user_reports 테이블 삭제
    op.drop_table("user_reports")

    # ### end Alembic commands ###

